version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3@sha256:8f43f180bad144922d3598a414748b6058b7a27359857f4731dccf994bf5e49e
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests